services:
   nuxeo:
    image: nuxeo-vntana:2023.2.0-SNAPSHOT
    ports:
      - "8080:8080"
      - "8787:8787"
    environment:
      - JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8787
      - NUXEO_DEV=true
      - NUXEO_PACKAGES=nuxeo-web-ui
      - NUXEO_CLID=${NUXEO_CLID}
    volumes:
      - ./conf.d:/etc/nuxeo/conf.d
      - data:/var/lib/nuxeo
volumes:
  data: {}

